-- Create students table
CREATE TABLE IF NOT EXISTS students (
  roll_no TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

-- Create days table
CREATE TABLE IF NOT EXISTS days (
  date TEXT PRIMARY KEY, -- Format: DD.MM.YYYY
  day_name TEXT NOT NULL,
  theme TEXT
);

-- Create assignments table
CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL REFERENCES days(date) ON DELETE CASCADE,
  role TEXT NOT NULL,
  student_roll_no TEXT NOT NULL REFERENCES students(roll_no) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE days ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow everyone to read, but only authenticated or a secret key to write)
-- For a simple project, we can allow read to everyone and write to authenticated if we set up Auth.
-- Or just allow all for now if the user hasn't set up Auth yet.
CREATE POLICY "Allow public read-only access on students" ON students FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access on days" ON days FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access on assignments" ON assignments FOR SELECT USING (true);

-- For admin operations, we'll use the secret key on the client or set up proper Auth.
-- For this migration, I'll provide policies that allow all for now, but advise the user to secure it.
CREATE POLICY "Allow all access to authenticated users" ON students FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all access to authenticated users" ON days FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all access to authenticated users" ON assignments FOR ALL USING (auth.role() = 'authenticated');
